Oop session2
meta-akshita-dixit/GET2018 pull request #8
Opened 2018-02-07 11:25 UTC by meta-akshita-dixit

Assignment for oop session 2

2018-02-19 10:49 UTC, metacube-shivang requested changes
Please see comments

2018-02-19 10:49 UTC, metacube-shivang commented on oop_Session2/Calculation.java
> +public class Calculation {
Classes should typically not be names as "verbs", but instead as "nouns". A class denotes an entity, a "doer", not the action itself. In this case, you can call it `Calculator` instead of `Calculation`.

2018-02-19 10:49 UTC, metacube-shivang commented on oop_Session2/IOFile.java
> +public class IOFile {
This class is not exactly representing a data structure such as a file, but instead operations on a file. A better name would be `IOFileManager`, or better still, `IOManager`

2018-02-19 10:49 UTC, metacube-shivang commented on oop_Session2/IOFile.java
> +		PrintWriter writer = new PrintWriter(new File("C:\\Users\\admin\\workspace\\OOP\\src\\oop_Session2\\participant-Result.txt"));
Don't hard-code file paths this way. Since the path will remain the same, either declare it as a `private static final` variable at the beginning of the class, or use a separate file for managing all the constants in one place.

But, given that you are reading the input file name via a constructor, ideally, you should also read the output file name from the constructor. This makes the class more generic and allows the calling code to specify a different path if it wants to save the file to a different location.

2018-02-19 10:49 UTC, metacube-shivang commented on oop_Session2/Question.java
> +	private String question;
We should also parse the question number as a field here, since it is already available in the input data. 

Although we know the question number based on the order in which we read it from the file, we shouldn't rely on it. Because that information is only available while the program is running. What if you were to save the questions to a database? When you read the questions back from the database, you will not know the correct order in which to read them.

2018-02-19 10:49 UTC, metacube-shivang commented on oop_Session2/Question.java
> +		if ( this.type. equalsIgnoreCase ("single") ) {
When comparing strings to a fixed literal (such as "single" in this case), it's good practice to invoke the method on the literal first. So, instead of this: `this.type.equalsIgnoreCase("single")`, do this: `"single".equalsIgnoreCase(this.type)`

Sometimes, the value in the variable may be `null`, in which case your expression will throw an NPE. But with the second approach, the NPE can be avoided.

2018-02-19 10:49 UTC, metacube-shivang commented on oop_Session2/Question.java
> +		return this.result;
Follow proper naming convention for "getter" method.

2018-02-19 10:49 UTC, metacube-shivang commented on oop_Session2/Result.java
> +	public void setResult(String option, String percent) {
Since we already have the count for each question, why do we need to set the percentage separately? You can have an internal method in this class itself that can calculate the percentage based on the counts.

2018-02-19 10:49 UTC, metacube-shivang commented on oop_Session2/SortQuestion.java
> +public class SortQuestion {
Sorting needs to be implemented using the `Comparable` interface. You don't actually need to write the sorting logic. This needs to be fixed before evaluation can be submitted.

2018-02-21 08:21 UTC, shivang-g commented on oop_Session2/Question.java
> +		return this.question.compareTo(ques.question);
Don't assume that an entity will not be null. Also, think about whether the comparison should be case-based or not.

2018-02-21 08:57 UTC, shivang-g reviewed
Review comments provided inline.

2018-02-21 08:58 UTC, closed without merging